services:

  hantacon_core:
    build: .
    container_name: hantacon_core_env
    user: "${UID}:${GID}"

    volumes:
      - ./workspace:/workspace

    working_dir: /workspace

    stdin_open: true
    tty: true

    command: bash


  hantacon_nextstrain:
    image: nextstrain/base
    container_name: hantacon_nextstrain_env
    user: "${UID}:${GID}"

    volumes:
      - ./workspace:/workspace

    working_dir: /workspace
    ports:
      - "4000:4000"

    stdin_open: true
    tty: true

    command: nextstrain view --allow-remote-access /workspace/auspice